### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by gfd6th** [dcblogdev/laravel-microsoft-graph#13]
Problem 1
    - Installation request for guzzlehttp/guzzle ^7.2 -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - dcblogdev/laravel-microsoft-graph v3.02 requires guzzlehttp/guzzle ^6 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - dcblogdev/laravel-microsoft-graph v3.02 requires guzzlehttp/guzzle ^6 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for dcblogdev/laravel-microsoft-graph ^3.02 -> satisfiable by dcblogdev/laravel-microsoft-graph[v3.02].

**Comment by dcblogdev** [comment]
I've applied a patch can you try it again.

**Comment by dcblogdev** [comment]
I had a typo in an early release stopping future releases from installing. This is fixed now.
