### ISSUE TITLE
Listener not fired

### ISSUE THREAD

**Issue by sirmadboy** [dcblogdev/laravel-microsoft-graph#15]
Hi, I tried to integrate login using ms graph. And I already follow steps from https://dcblog.dev/docs/laravel-microsoft-graph/msgraph/login-with-msgraph.
But the listener seems not fired because when I check database, there's no new user record.

**Comment by sirmadboy** [comment]
My fault, I misconfigured my service provider. It's working now.

**Comment by vizcainomc66** [comment]
Hi! I have the same problem. Can you post here what was your solution? Maybe I did the same mistake.
