### ISSUE TITLE
BaseUrl beta or v1.0?

### ISSUE THREAD

**Issue by webstudios1** [dcblogdev/laravel-microsoft-graph#17]
Hi, would just say that this package is awsome...

Just wondering if this is a issue or a permanently change.
In the bottom om the documentation on MsGraph, says that only the endpoint should be added and the package provides the base with beta version selected, but in the source code the v1.0 is provided.

MsGraph.php
`    protected static $baseUrl = 'https://graph.microsoft.com/v1.0/';
`

**Comment by dcblogdev** [comment]
thanks, sorry for the delay in responding.

I released this with beta original but changed it to v1 from a pull request. v1 is stable and beta should not be used in production since its in preview and could change.
