### ISSUE TITLE
Any way to get the photo using responseType = blob?

### ISSUE THREAD

**Issue by fzhan** [dcblogdev/laravel-microsoft-graph#21]
Hi,

I'm trying to get the photo using:

MsGraph::get('me/photo/$value');

But the response is NULL, I've checked the other online documents, such request need to have a different responseType.

Any ideas?

**Comment by dcblogdev** [comment]
Yes, I've changed the inner works so when a binary response is detected its returned directly rather then trying to decode the response.

You can then pass the response into a base64 image:

```php
$photo = MsGraph::get('me/photo/$value');
echo "<img src='data:image/png;base64,".base64_encode($photo)."'>";
```

**Comment by jcfrazier6** [comment]
I am trying to the all users' data and combine their photos.  Per the below, I am running the first call to get the user data. the second call is getting the user's photo based on id. All is combined, which works fine. My issue is that I can't get the photo to show onside the page table. I have tried using what you posted below but that isn't working. Any help is appreciated.



$Employees = MSGraph::get('users?$select=id,displayName,userPrincipalName');

$combinedResults = [];

foreach ($Employees['value'] as $Employee) {
    $userId = $Employee['id'];

    // Retrieve employee photo
    $Photos = MSGraph::get("users/{$userId}/photo/\$value");

    // Combine the results
    $combinedResults[] = [
        'id' => $userId,
        'displayName' => $Employee['displayName'],
        'userPrincipalName' => $Employee['userPrincipalName'],
        'photo' => $Photos, 
    ];
}




 @foreach($combinedResults as $Employee)
      <tr>
          <td>{{ $Employee['id'] }}</td>
          <td>{{ $Employee['displayName'] }}</td>
          <td>{{ $Employee['userPrincipalName'] }}</td>
          <td><img src='data:image/png;base64,{{ base64_encode($Employee['photo']) }}' alt='User Photo'></td>
      </tr>
  @endforeach
