### ISSUE TITLE
Local issue

### ISSUE THREAD

**Issue by akauhovs** [dcblogdev/laravel-microsoft-graph#24]
Realy good pacakge, but in first minutes I came to a problem, returning errors on contacts email etc.

Digging emails()->get() I see this:

```
 $folder = $folderId == null ? 'Inbox' : $folderId;
        //get inbox from folders list
        $folder = MsGraph::get("me/mailFolders?\$filter=startswith(displayName,'$folder')");
```

But my "Inbox" folder is in other language rather than english, and it returns error. So if we take a look to microsoft docs ->
GET /me/mailFolders/inbox

`$folder = MsGraph::get("me/mailFolders/$folder");`

Like so, everything works fine. 
Maybe in future should think about it.

**Comment by dcblogdev** [comment]
You should be able to provide the name of your inbox in your language as the first option:

```php
$emails = MsGraph::emails()->get('your-inbox-name');
```

When no option is set then inbox will be used.
