### ISSUE TITLE
User is not being added to database

### ISSUE THREAD

**Issue by Devannn** [dcblogdev/laravel-microsoft-graph#26]
Hello, when i try to log in with microsoft everything works fine and i get redirected to my MSGRAPH_LANDING_URL= but the account is not being added to the database.

**Comment by dcblogdev** [comment]
I've run through this and it's working on a new install, the user_id will be blank but I can see the email and token

**Comment by rifton007** [comment]
@Devannn 
Do you speak about the token or user informations ?

**Comment by dcblogdev** [comment]
The user_is is empty when login in with graph but the email and tokens will be set, you can see this in this video.

**Comment by rifton007** [comment]
I just look at for your video @dcblogdev it is very appreciated 👍

However, I think that I have the same problem of @Devannn.
The access_token adds well on ms_graph_token table, but the users table keep empty.
Also when a new user logs, the previous token is replaced by the new token although if user is different.

So, if you look at `NewMicrosoft365SignInListener`, normally the user should be add in `users` table.
I put this video to expose the problem.
https://user-images.githubusercontent.com/2601347/183756367-eaacf1be-d8e5-4e0f-bd5e-f280acd7bad9.mp4

Thanks,

**Comment by dcblogdev** [comment]
ahh I see what you mean, thanks for helping to clear this up

**Comment by rifton007** [comment]
I think there are other problems in the code.

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test@domissori.fr' for key 'users_email_unique'`
```php
if ($token->user_id == null) {
    $user = User::create(['name'     => $event->token['info']['displayName'],
        'email'    => $event->token['info']['mail'],
         'password' => '']);
```

This Is normal because `$token->user_id` always `null`, but if the user did connected in the past he is aleary exist on `users` table with a identique email at the email of $token.

---

Do you want to I create a new issue or we continue here ?

**Comment by dcblogdev** [comment]
when the event listerner is added to the event service provider that appears to solve the problem. If not please open a new issue.
