### ISSUE TITLE
"Array to string conversion" error when querying

### ISSUE THREAD

**Issue by NWMF** [dcblogdev/laravel-microsoft-graph#27]
Hello, I keep getting this error whenever I try to run:

`$emails = MsGraph::emails()->get([
            "\$orderby" => "displayName",
            "\$top" => 100,
            "\$skip" => 0,
            "\$count" => "true",
]);`

The error page:
https://flareapp.io/share/w5BjNlD5#F51

It also happens when running for Contacts, Calendar etc...

I'm using Laravel 9.17.0 - PHP 8.1.6 running on localhost using Valet for Windows.

Permissions are all good, authentication is working well too.

**Comment by dcblogdev** [comment]
the get method expected a folder id and then an array of options ie:

```
$emails = MsGraph::emails()->get('inbox', ["\$top" => 100, "\$skip" => 0, "\$count" => "true" ]);
```

I need to update the docs.

**Comment by MilesHart** [comment]
I found this also works.


`$rtn = MsGraph::emails()->top(20)->get();
`
