### ISSUE TITLE
error:invalid_client

### ISSUE THREAD

**Issue by AnthonyScorch** [dcblogdev/laravel-microsoft-graph#34]
Having followed the installation and graph application setup a few times now, I am constantly getting the error error:invalid_client after being redirected back to the /connect endpoint post sign-in. I have checked al of the details several times and have created a few different secrets but always recieve the same error, does this package still work with the current graph API?

**Comment by dcblogdev** [comment]
invalid_client must match your client_id field

so `MSGRAPH_CLIENT_ID` should match what you have in your tenancy

<img width="417" alt="CleanShot 2022-09-03 at 11 44 07@2x" src="https://user-images.githubusercontent.com/1018170/188266940-2765ed54-3db2-4ff4-90de-e3bab736efa9.png">

**Comment by AnthonyScorch** [comment]
Thanks David, I still cant get it to return anything other than that error but now I know it is on the azure side if the integration is still functional, yes I did use that value from within the azure portal.

**Comment by AnthonyScorch** [comment]
Got it, the config file is written but not updated within the cache directory, Quite why cache:clear hadnt sorted it I am not sure but manually changing the config.php file has fixed it.
