### ISSUE TITLE
Database connection [default] not configured.

### ISSUE THREAD

**Issue by angelothegreat13** [dcblogdev/laravel-microsoft-graph#35]
Database connection errors keep popping up even though I already  configured my database correctly, by the way, this error only appears in live site

![image](https://user-images.githubusercontent.com/26960543/188202361-077d270f-e654-4844-91b6-56af91427775.png)

**Comment by angelothegreat13** [comment]
![image](https://user-images.githubusercontent.com/26960543/188202323-13e40422-3e5d-4a31-8385-c1fd5be2469e.png)

**Comment by dcblogdev** [comment]
I've been thinking about changing the default option from default to mysql.

in your .env file add 

```
MSGRAPH_DB_CONNECTION=mysql
```

to set the connection to use a connection called mysql.

**Comment by angelothegreat13** [comment]
> I've been thinking about changing the default option from default to mysql.
> 
> in your .env file add
> 
> ```
> MSGRAPH_DB_CONNECTION=mysql
> ```
> 
> to set the connection to use a connection called mysql.

It works, Thanks :-)
