### ISSUE TITLE
Migrations failing

### ISSUE THREAD

**Issue by PaulMcITS** [dcblogdev/laravel-microsoft-graph#45]
Hi,

The published migrations fail (in laravel 9 anyway) with Cannot declare class create_ms_graph_tokens_table, because the name is already in use

I had to change the class name to CreateMsGraphTokensTable to get the migration to run.

Cheers!

**Comment by Kristianmarku** [comment]
I have the same issue in Laravel 9, I tried changing the class name but still not working.

**Comment by musznik** [comment]
bump, same issue, package not working.

**Comment by dcblogdev** [comment]
Strange this used to work perfectly, but you're right @musznik changing the migration to an anonymous migration works.

I'll push a release to change this in the package.

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ms_graph_tokens', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->string('email')->nullable();
            $table->text('access_token');
            $table->text('refresh_token')->nullable();
            $table->string('expires');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ms_graph_tokens');
    }
};
```

**Comment by dcblogdev** [comment]
I've just released this change https://github.com/dcblogdev/laravel-microsoft-graph/releases/tag/v3.1.7

**Comment by movcmpret** [comment]
Faced this issue with laravel 8 and dcblogdev/laravel-microsoft-graph v**3.2.0**

downgrade to **3.1.5** solved it
