### ISSUE TITLE
Issues with Laravel 9 

### ISSUE THREAD

**Issue by Kristianmarku** [dcblogdev/laravel-microsoft-graph#46]
I attempted to integrate it in Laravel 9 following the instructions, but clearly the package has multiple errors for L9.
If this repository isn't abandoned, I would appreciate an update to support L9.

**Comment by MahaEast** [comment]
I’ve only ran intro problems with the migration and listeners. But if You change and add it manually, it works. My problem is the laravel session and user validation. It is possible for a user to login with the last logged in user data. So i have to build my own solution to log in with AD. So i can’t recommend this   Module for security  reasons.

**Comment by dcblogdev** [comment]
There is an issue with the migration, I've just pushed a release to change the default migration to an anonymous migration.

I want to update the docs too some of the pages are not as clear as they could be.

**Comment by Kristianmarku** [comment]
@dcblogdev Thanks for the hard work mate. If you could also update the docs that would be awesome and much appreciated.
