### ISSUE TITLE
Moving emails in a sharedmailbox

### ISSUE THREAD

**Issue by MilesHart** [dcblogdev/laravel-microsoft-graph#53]
I want to move emails (by ID) from the inbox to a another foler in the same mailbox.

Does anyone have any pointers for this?

Much appreciated.

**Comment by dcblogdev** [comment]
You can do this by using `MsGraph::post("me/messages/$id/move", ['destinationId' => $folderId]);`

see https://learn.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=http for more details
