### ISSUE TITLE
Refreshing the token trough artisan command

### ISSUE THREAD

**Issue by galabl** [dcblogdev/laravel-microsoft-graph#58]
Could you please help me w/ this or provide some documentation since I can't find any.

I've tried using the msgraph:keep-alive command but it does nothing so my token always expires and I need to reconnect manually every time.

Thanks in advance.

**Comment by dcblogdev** [comment]
Apologies, it's taken so long to look at this, I can see the params being passed to the command internally we're not in the correct order. I've updated and will do a release shortly.
