### ISSUE TITLE
Mime type on attachments

### ISSUE THREAD

**Issue by erotundo** [dcblogdev/laravel-microsoft-graph#62]
Hi all!

It's possible set the mime-type of the attachment??? I'm trying send a ical as attachment but everytime returns a error related with the mime-type

**Comment by dcblogdev** [comment]
Yes you can set its contentType inside the attachment body:

```
{
  "contentType": "string",
  "id": "string (identifier)",
  "isInline": true,
  "lastModifiedDateTime": "String (timestamp)",
  "name": "string",
  "size": 1024
}
```

see https://learn.microsoft.com/en-us/graph/api/resources/attachment?view=graph-rest-1.0
