### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by garras16** [dcblogdev/laravel-microsoft-graph#68]
I have issue this month when i want to upload my file (ZIP) to Onedrive. On Laravel Log it's showing 

**Cannot use object of type stdClass as array {"userId":16,"exception":"[object] (Error(code: 0): Cannot use object of type stdClass as array at /home/.../public_html/.../vendor/dcblogdev/laravel-microsoft-graph/src/Resources/Files.php:72)**

how to fix it?

**Comment by dcblogdev** [comment]
unable to replicate this.
