### ISSUE TITLE
Invalid grant type

### ISSUE THREAD

**Issue by yudha47** [dcblogdev/laravel-microsoft-graph#69]
Hii, i have the issue after login pop up microsoft is success, the response error is like this, can you help me for this issue ?, i'm using version 3.2.0

![Xnip2023-11-23_15-01-25](https://github.com/dcblogdev/laravel-microsoft-graph/assets/57881312/d6ae7403-9047-48a9-b53a-bcc82f2097d0)

**Comment by narimanmuhsin** [comment]
@yudha47 same issue , did you fixed ?

**Comment by dcblogdev** [comment]
Are you sure both MSGRAPH_CLIENT_ID and MSGRAPH_SECRET_ID are set correctly?
