### ISSUE TITLE
$userModel with type problems

### ISSUE THREAD

**Issue by antoniopaisfernandes** [dcblogdev/laravel-microsoft-graph#71]
Hi,

Looking at the latest release, I think the `object` type is not ok:

![image](https://github.com/dcblogdev/laravel-microsoft-graph/assets/6171197/a16e40b5-f004-42f4-be7c-5de14c03f8a9)

The static $userModel is a `string` but the method type is an `object`.

Can it keep being a string?

**Comment by dcblogdev** [comment]
Thanks, I've updated this.

https://github.com/dcblogdev/laravel-microsoft-graph/releases/tag/v3.2.6
