### ISSUE TITLE
Posting to /users/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/onlineMeetings returns string

### ISSUE THREAD

**Issue by ShaunWilders** [dcblogdev/laravel-microsoft-graph#72]
When trying to create a Teams meeting, it works, but the returned JSON is a string so the following error is generated...

_Dcblogdev\MsGraph\MsGraphAdmin::isJson(): Argument #1 ($data) must be of type object, string given, called in C:\xampp\htdocs\magna\vendor\dcblogdev\laravel-microsoft-graph\src\MsGraphAdmin.php on line 189_

Code in use...

```
$graphresponse = MsGraphAdmin::post("/users/". config('msgraph.MeetingUserId') ."/onlineMeetings", [
            'subject' => $booking->subject,
            'startDateTime' => $booking->start_time,
            'endDateTime' => $booking->end_time,
        ]);
```

Is there a reason for line 165 being specified as an object?

If I take out "object" it all works fine...

`protected function isJson(/*object*/ $data): bool`

**Comment by boskee** [comment]
Same with get to user/

**Comment by ShaunWilders** [comment]
@dcblogdev - any chance of a quick fix?

**Comment by dcblogdev** [comment]
I've removed the object type hint, thank for letting me now. 

https://github.com/dcblogdev/laravel-microsoft-graph/releases/tag/v3.2.6
