### ISSUE TITLE
difficulty with this endpoint

### ISSUE THREAD

**Issue by ApuRed** [dcblogdev/laravel-microsoft-graph#8]
I am trying to use this endpoint to be able to add a student to a class, but I get an error, I have tried modifying the lines in almost every way, I have tried to understand the API but it is still somewhat complicated for me, I have looked for the error it sends in many places, without any success.

```
$Estudiante = [
"@odata.id" => "https://graph.microsoft.com/beta/education/users/{student_id}"
];
$Resultado = MsGraphAdmin::post('education/classes/{classes_id}/members/$ref', $Estudiante);
dd($Resultado);
```
here the error
```
{#1252 ▼
  +"error": {#1230 ▼
    +"code": "AccessDenied"
    +"message": "Required claim values are not provided."
    +"innerError": {#1261 ▼
      +"request-id": "a7c74dd9-7fb4-4c6b-b3c9-6c6398916001"
      +"date": "2020-06-03T14:42:39"
    }
  }
}
```

I turn to you since I am using your library which helps me a lot with the other APIs that I am using from Microsoft.

**Comment by dcblogdev** [comment]
Hi, you may have already seen this but this post looks to answer this https://stackoverflow.com/questions/49415969/accessdenied-required-claim-values-are-not-provided-when-accessing-education-us

also have you set these scopes in the permissions:

> EduRoster.ReadWrite.All plus Member.Read.Hidden

I assume {classes_id} is replaced with the actual class id?
